---   
- name: execute show run command on the cx switches.          
  hosts: all
  roles: 
   - role: arubanetworks.aoscx.aoscx_role
  vars:                                           
   ansible_host:
     -switch: 10.202.217.11
     -switch: 10.202.217.12
     -switch: 10.202.216.12
     -switch: 10.202.216.13
     -switch: 10.202.216.14
     loop: "{{ ansible_host }}"
  gather_facts: False          
  task:
    aoscx_command:
      commands: ['show run'] 
         
    

# ansible-galaxy collection install arubanetworks.aoscx:3.0.0
# ansible -i <inventory_name>.yml "all" -m ping
# ansible -i <inventory_name>.yml "all" -m ansible.builtin.ping
# run the playbook using "ansible-playbook -i <inventory_name>.yml <playbook_name>.yml --ask-become-pass [-vvvv]"
    # the more v's added, the more detailed output is shown. this is useful for debugging/tshooting
    # ask-become-pass requests for the password for the target device(s) specified in the playbook to be entered
# gather_facts are Ansible facts are data related to your remote systems, including operating systems, IP addresses, attached filesystems, and more. It is enabled by default